# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70534e6a394ba535d06a3da4dffb57771ba174dd56697a2b723e09d8a3dfa3e6bc71d6eabbf306697df0ab7a80518c5abd730cf6e53e1f0ea856e62374729cf2

test:
  secret_key_base: f753e4dddff9577a61c788008c45f9e02469c1eebe35537ac7cd187cde64a4854401e36fadd72e9e1bcc61c5d7e4aa678565764d4995a00b043b80dc7575b819

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
